# .github/workflows/ci.yml
name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' # Versão Python para rodar no CI

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 2. Black (Formatação de código)
    - name: Run Black (code formatter)
      run: |
        black --check --diff .
      
    # 2. Flake8 (Análise de estilo e lint)
    - name: Run Flake8 (style guide enforcement)
      run: |
        flake8 .
        
    # 2. Pytest (Execução de testes)
    - name: Run Pytest (unit tests)
      run: |
        pytest 
